name: maze
description: A simple maze game in Flutter. It also serves as a CustomPainter example.
version: 4.0.0
homepage: https://github.com/KyleKun/maze
repository: https://github.com/KyleKun/maze

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  http: ^0.13.0
  universal_io: ^2.0.0
  back_button_interceptor: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.0

flutter:
